# Generated by Django 3.0.2 on 2020-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200411_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
