# Generated by Django 3.0.2 on 2020-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_items_cust_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='cust_name',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
