# Generated by Django 3.0.2 on 2020-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, 'ยังไม่จ่าย'), (1, 'จ่ายแล้ว')], default=False),
        ),
    ]
