# Generated by Django 3.0.2 on 2020-04-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200418_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order_products',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
        migrations.AddField(
            model_name='order_products',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
