# Generated by Django 3.0.2 on 2020-04-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_order_products_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
