# Generated by Django 3.0.2 on 2020-04-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200422_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cust_name',
            new_name='customer',
        ),
    ]
