# Generated by Django 3.0.5 on 2020-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200422_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_file',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
