# Generated by Django 3.0.5 on 2020-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_payment_pay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
